<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gender extends Model
{
    use HasFactory;
    protected $table = 'genders';
    protected $primaryKey = 'id';
    public $timestamps = true;

    protected $guarded = [];//usar esto si no hay validacion en los form,para crear o modificar datos

    protected $fillable = [
        'id',
        'gender',
    ];

    public function getRouteKeyName()
    {
        //return 'title'; // TODO: Change the autogenerated stub
        return 'gender';//atributo de la tabla para que se realice la consulta
    }

    //relacion entre padre e hijo
    public function mangas()
    {
        return $this->belongsToMany('App\Models\Manga','gender_manga','gender_id','manga_id')->using(GenderManga::class)->withTimestamps();
    }
}
